### ISSUE TITLE
1.1 无法通过验证码

### ISSUE THREAD

**Issue by sbilly** [louisslee/sgcc_electricity#3]
sgcc_electricity 版本：1.1
HA 版本：

```
Home Assistant 2022.11.2
Supervisor 2022.11.dev0401
前端版本： 20221108.0 - latest
```

安装执行后始终没有搜到 `sensor.last_electricity_usage` 这个实体。打开 DEBUG 日志以后可以看到，启动后日志不断刷，内容基本是重复的。1.0 也没有正常工作，现象类似。

- 100% 确定手机号码和密码正确（用这个手机号和密码成功登录移动 iOS 的 app）
- 从日志看，感觉是没有成功识别验证码。

从里面可以找到报错信息如下：

```
2022-11-11 18:18:25  [DEBUG   ] ---- Finished Request
2022-11-11 18:18:26  [DEBUG   ] ---- Login failed, maybe caused by invalid captcha, 0 retry times left.
2022-11-11 18:18:26  [ERROR   ] ---- state-refresh task failed, reason is Login failed, maybe caused by incorrect phone_number and password
Traceback (most recent call last):
  File "./main.py", line 27, in run_task
    user_id_list, balance_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list = data_fetcher.fetch()
  File "/app/data_fetcher.py", line 33, in fetch
    raise e
  File "/app/data_fetcher.py", line 30, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 47, in _fetch
    self._login(driver)
  File "/app/data_fetcher.py", line 115, in _login
    raise Exception("Login failed, maybe caused by incorrect phone_number and password")
Exception: Login failed, maybe caused by incorrect phone_number and password
^CTraceback (most recent call last):
  File "./main.py", line 75, in <module>
    main()
  File "./main.py", line 23, in main
    time.sleep(1)
KeyboardInterrupt
```

**Comment by louisslee** [comment]
看起来像是网络、性能问题造成的。
建议进入container里，把const.py里边的LOGIN_EXPECTED_TIME改成20+，然后打开data_fetcher.py ，拉下边，把手机号、密码填上，你在container执行下python3 data_fetcher.py 。看看可行否

**Comment by sbilly** [comment]
这么执行还是最后报错

```bash
docker run --rm -ti --name sgcc_electricity -e LOGIN_EXPECTED_TIME=30 -e PHONE_NUMBER="xxxx" -e LOG_LEVEL="DEBUG" -e PASSWORD="xxxx" -e HASS_URL="http://xxxx/" -e HASS_TOKEN="xxxx" sgcc_electricity:1.1
```
报错信息如下：

```
2022-11-11 18:34:22  [DEBUG   ] ---- Login failed, maybe caused by invalid captcha, 0 retry times left.
Traceback (most recent call last):
  File "/app/data_fetcher.py", line 30, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 47, in _fetch
    self._login(driver)
  File "/app/data_fetcher.py", line 115, in _login
    raise Exception("Login failed, maybe caused by incorrect phone_number and password")
Exception: Login failed, maybe caused by incorrect phone_number and password
2022-11-11 18:34:22  [ERROR   ] ---- Webdriver quit abnormly, reason: Login failed, maybe caused by incorrect phone_number and password. 3 retry times left.
^CTraceback (most recent call last):
  File "/app/data_fetcher.py", line 30, in fetch
    return self._fetch()
  File "/app/data_fetcher.py", line 47, in _fetch
    self._login(driver)
  File "/app/data_fetcher.py", line 115, in _login
    raise Exception("Login failed, maybe caused by incorrect phone_number and password")
Exception: Login failed, maybe caused by incorrect phone_number and password

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./main.py", line 75, in <module>
    main()
  File "./main.py", line 20, in main
    run_task(fetcher, updator)
  File "./main.py", line 27, in run_task
    user_id_list, balance_list, last_daily_usage_list, yearly_charge_list, yearly_usage_list = data_fetcher.fetch()
  File "/app/data_fetcher.py", line 37, in fetch
    time.sleep(wait_time)
KeyboardInterrupt
2022-11-11 18:34:32  [DEBUG   ] ---- cleaning up pid 24
2022-11-11 18:34:32  [DEBUG   ] ---- cleaning up pid 90
```

**Comment by louisslee** [comment]
请尝试下在PC端国网上是否能正常登陆 https://www.95598.cn/osgweb/login

**Comment by louisslee** [comment]
> docker run --rm -ti --name sgcc_electricity -e LOGIN_EXPECTED_TIME=30 -e PHONE_NUMBER="xxxx" -e LOG_LEVEL="DEBUG" -e PASSWORD="xxxx" -e HASS_URL="http://xxxx/" -e HASS_TOKEN="xxxx" sgcc_electricity:1.1

另外login_expected_time不是环境变量，无法通过这种方式制订

**Comment by sbilly** [comment]
PC 上登录不上 WEB 界面。即使用 app 登录后扫描 WEB 的二维码也不能登录 PC 的 WEB 界面。

大概率是这个问题。

> 试了那么多次，极大概率不是验证码问题。ddddocr尽管会有失败的情况，但识别率还是很高的。 请尝试下在PC端国网上是否能正常登陆 https://www.95598.cn/osgweb/login
> 
> 请确保在web端登陆没有问题，并绑定好户号。

**Comment by louisslee** [comment]
嗯嗯，那你先注册下，绑定好户号，再使用这个应用吧。

**Comment by sbilly** [comment]
WEB 上提示账号注册过，找回密码重新设置密码，也是一样。已经打电话报故障。等国网反馈了再说。
